env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/
    binary: "{{.ProjectName}}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'